### PR TITLE
Handle unset GOPATH

### PR DESCRIPTION
**Pull request by eskwayrd**
Even though Go itself defaults to `~/go` when `GOPATH` is not set, some of the dependencies do not use the same default. This change helps by providing a default in the Makefile.

### CODE REVIEW

**Comment by geek1011** [comment]
This won't work due to golang/go#14566. BookBrowser uses vendoring for its dependencies, and vendoring does not work outside GOPATH.

**Comment by eskwayrd** [comment]
Apologies for the incorrect env var reference. Now fixed.

**Comment by eskwayrd** [comment]
If `GOPATH` is unset, `govendor sync` emits:
```
govendor sync
Error: Missing GOPATH. Check your environment variable GOPATH.
govendor sync
        Ensures the contents of the vendor folder matches the vendor file.
        Options:
                -n           dry run, print out action only
                -insecure    allow downloading over insecure connection
                -v           verbose output
```
So you can't use vendoring without a defined `GOPATH`.

This change sets `GOPATH` to the default value that Go uses, but *only* if it is unset. Do you see a downside to this change? I'm not worried if you don't accept it, but I would like to understand what I may be missing.

**Comment by geek1011** [comment]
@eskwayrd Yes, that is correct, but that's only half of it. Govendor will sync if there is a GOPATH, but go build will not work with the synced deps unless BookBrowser itself is in the GOPATH.

**Comment by eskwayrd** [comment]
Ah. I've just been learning about Go's dependency issues, since all of BookBrowser's internal imports use absolute paths (as required), which makes working on forked projects a PITA. I'll close this PR since, as you say, it is an incomplete solution.

**Comment by geek1011** [comment]
Yep, you are correct. Thanks for your contributions anyways!

**Pull request closed without merging**
